### ISSUE TITLE
[Bug] Extra Network > Textual Inversion - Tab error

### ISSUE THREAD

**Issue by ostap667inbox** [lobehub/sd-webui-lobe-theme#368]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

Extra Network > Textual Inversion tab
Error "Nothing here. Add some content to the following directories: C:\stable-diffusion-webui\embeddings"
But there are many Textual Inversion files in this folder.

![chrome_eK848Ip32H](https://github.com/lobehub/sd-webui-lobe-theme/assets/123593542/07299356-0e8d-445b-ac53-3d32e375f9c6)

### 📝 补充信息 | Additional Information

`Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
[Lobe]: Initializing Lobe
Startup time: 73.2s (prepare environment: 55.7s, import torch: 4.0s, import gradio: 1.5s, setup paths: 0.9s, initialize shared: 0.2s, other imports: 1.1s, setup codeformer: 0.3s, load scripts: 3.3s, create ui: 4.0s, gradio launch: 1.4s, add APIs: 0.2s, app_started_callback: 0.5s).
Loading VAE weights specified in settings: D:/install/NEURAL/VAE\sdxl_vae_fp16-fix.safetensors
Applying attention optimization: xformers... done.
Model loaded in 14.8s (load weights from disk: 2.1s, create model: 0.5s, apply weights to model: 7.7s, apply channels_last: 0.3s, apply half(): 0.1s, load VAE: 0.9s, load textual inversion embeddings: 1.4s, calculate empty prompt: 1.7s).
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "C:\stable-diffusion-webui\modules\ui_extra_networks.py", line 400, in refresh
    ui.pages_contents = [pg.create_html(ui.tabname) for pg in ui.stored_extra_pages]
  File "C:\stable-diffusion-webui\modules\ui_extra_networks.py", line 400, in <listcomp>
    ui.pages_contents = [pg.create_html(ui.tabname) for pg in ui.stored_extra_pages]
  File "C:\stable-diffusion-webui\modules\ui_extra_networks.py", line 162, in create_html
    self.items = {x["name"]: x for x in self.list_items()}
  File "C:\stable-diffusion-webui\modules\ui_extra_networks.py", line 162, in <dictcomp>
    self.items = {x["name"]: x for x in self.list_items()}
  File "C:\stable-diffusion-webui\extensions-builtin\Lora\ui_extra_networks_lora.py", line 69, in list_items
    for index, name in enumerate(networks.available_networks):
RuntimeError: dictionary changed size during iteration`

**Comment by Teenspirit** [comment]
I'm getting this as well, was working fine until it stopped showing embeddings and LoRAs, checkpoints still there.

**Comment by KingPungy** [comment]
Clearing the cookies of the page fixes this as well

**Comment by ostap667inbox** [comment]
> Clearing the cookies of the page fixes this as well

Didn't help. After deleting cookies the textual inversion tab is still blank with this message:
![image](https://github.com/lobehub/sd-webui-lobe-theme/assets/123593542/d313e36c-171c-476d-b638-17e24170db98)

The following messages are displayed in the console when trying to update a tab:
```
---
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\stable-diffusion-webui\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\fastapi\applications.py", line 273, in __call__
    await super().__call__(scope, receive, send)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 109, in __call__
    await response(scope, receive, send)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\starlette\responses.py", line 270, in __call__
    async with anyio.create_task_group() as task_group:
  File "C:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "C:\stable-diffusion-webui\venv\lib\site-packages\starlette\responses.py", line 273, in wrap
    await func()
  File "C:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 134, in stream_response
    return await super().stream_response(send)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\starlette\responses.py", line 255, in stream_response
    await send(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\errors.py", line 159, in _send
    await send(message)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 490, in send
    output = self.conn.send(event=response)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\h11\_connection.py", line 468, in send
    data_list = self.send_with_data_passthrough(event)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\h11\_connection.py", line 483, in send_with_data_passthrough
    raise LocalProtocolError("Can't send data when our state is ERROR")
h11._util.LocalProtocolError: Can't send data when our state is ERROR
```
