### ISSUE TITLE
[Question] 模型每次都加載不出來，怎麼回事？

### ISSUE THREAD

**Issue by punskhit120** [lobehub/sd-webui-lobe-theme#410]
### 🧐 问题描述 | Proposed Solution

![截圖 2023-09-12 上午9 58 44](https://github.com/lobehub/sd-webui-lobe-theme/assets/24973236/ba48f6a5-5912-4e07-a70f-ece910294912)

模型每次都加載不出來，怎麼回事？

**Comment by Access-Denied-20** [comment]
我也是，Extensions-Installed 页面也是一直在加载

**Comment by BylethC** [comment]
同有该问题，可以确定是lobe主题导致的问题，因为只要关闭lobe主题，就会恢复正常

**Comment by Access-Denied-20** [comment]
> 排查方法，将 webui 和 lobe theme 更新到最新，如果依然有问题，尝试排查↓是否和其他插件存在冲突

应该是和controlNet冲突，停用controlNet就正常。这下得二选一了

**Comment by canisminor1990** [comment]
最新的controlnet么，我这边也安装了 应该没问题

**Comment by Access-Denied-20** [comment]
> 最新的controlnet么，我这边也安装了 应该没问题
又排除了一遍，开启了controlNet关了别的一些扩展又可以了
![image](https://github.com/lobehub/sd-webui-lobe-theme/assets/50802292/cc566059-67d0-4f94-a1c1-eb9e89c81b4b)

**Comment by Access-Denied-20** [comment]
> > 最新的controlnet么，我这边也安装了 应该没问题 又排除了一遍，开启了controlNet关了别的一些扩展又可以了
> > ![图像](https://user-images.githubusercontent.com/50802292/267923351-cc566059-67d0-4f94-a1c1-eb9e89c81b4b.png)

同样的设置下午还可以，现在又不行了，难搞

**Comment by kukudoe** [comment]
老样子，好像并没有修复

**Comment by n0kovo** [comment]
+1

**Comment by NaughtDZ** [comment]
+1
以下是我用的插件，额外网络无限加载，已安装的扩展插件也是无限加载
2024/01/09  21:58    <DIR>          a1111-sd-webui-tagcomplete
2024/01/10  23:42    <DIR>          adetailer
2023/11/24  10:28    <DIR>          multidiffusion-upscaler-for-automatic1111
2024/01/06  23:52    <DIR>          OneButtonPrompt
2023/11/24  10:28    <DIR>          prompt_translator
2024/01/12  13:00    <DIR>          sd-civitai-browser-plus
2023/11/24  10:28    <DIR>          sd-webui-3d-open-pose-editor
2023/12/20  23:54    <DIR>          sd-webui-animatediff
2023/11/24  10:28    <DIR>          sd-webui-aspect-ratio-helper
2024/01/12  13:00    <DIR>          sd-webui-controlnet
2024/01/07  11:35    <DIR>          sd-webui-deepdanbooru-object-recognition
2023/11/24  10:30    <DIR>          sd-webui-depth-lib
2024/01/08  17:58    <DIR>          sd-webui-e621-prompt
2023/11/24  17:45    <DIR>          sd-webui-freeu
2024/01/12  18:41    <DIR>          sd-webui-infinite-image-browsing
2024/01/12  17:48    <DIR>          sd-webui-lobe-theme
2023/11/24  10:30    <DIR>          sd-webui-oldsix-prompt
2023/12/26  22:37    <DIR>          sd-webui-openpose-editor
2024/01/06  23:52    <DIR>          sd-webui-reactor
2023/11/24  10:28    <DIR>          sd_delete_button
2023/11/27  21:34    <DIR>          stable-diffusion-webui-localization-zh_CN
2023/11/24  10:30    <DIR>          stable-diffusion-webui-localization-zh_Hans
2023/11/24  10:30    <DIR>          stable-diffusion-webui-promptgen
2023/11/24  10:30    <DIR>          stable-diffusion-webui-state
2023/11/24  10:30    <DIR>          stable-diffusion-webui-wildcards
2024/01/07  11:39    <DIR>          ultimate-upscale-for-automatic1111
2023/11/24  10:30    <DIR>          webui-qrcode-generator

*****************************************
亲测用--no-gradio-queue 可以解决但是会导致一堆报错：
To create a public link, set `share=True` in `launch()`.
Loading VAE weights specified in settings: I:\stable-diffusion-webui\models\VAE\kl-f8-anime2.vae.pt
Applying attention optimization: xformers... done.
🤯 LobeTheme: Initializing...
Startup time: 38.0s (prepare environment: 14.1s, import torch: 4.8s, import gradio: 1.8s, setup paths: 1.2s, initialize shared: 0.3s, other imports: 1.0s, setup codeformer: 0.3s, list SD models: 0.2s, load scripts: 11.0s, create ui: 1.9s, gradio launch: 1.3s).
Model loaded in 7.6s (load weights from disk: 0.2s, create model: 1.0s, apply weights to model: 1.4s, load VAE: 0.3s, load textual inversion embeddings: 4.5s, calculate empty prompt: 0.1s).
ERROR:asyncio:Exception in callback H11Protocol.timeout_keep_alive_handler()
handle: <TimerHandle when=26031.187 H11Protocol.timeout_keep_alive_handler()>
Traceback (most recent call last):
  File "I:\stable-diffusion-webui\venv\lib\site-packages\h11\_state.py", line 249, in _fire_event_triggered_transitions
    new_state = EVENT_TRIGGERED_TRANSITIONS[role][state][event_type]
KeyError: <class 'h11._events.ConnectionClosed'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "I:\stable-diffusion-webui\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 363, in timeout_keep_alive_handler
    self.conn.send(event)
  File "I:\stable-diffusion-webui\venv\lib\site-packages\h11\_connection.py", line 468, in send
    data_list = self.send_with_data_passthrough(event)
  File "I:\stable-diffusion-webui\venv\lib\site-packages\h11\_connection.py", line 493, in send_with_data_passthrough
    self._process_event(self.our_role, event)
  File "I:\stable-diffusion-webui\venv\lib\site-packages\h11\_connection.py", line 242, in _process_event
    self._cstate.process_event(role, type(event), server_switch_event)
  File "I:\stable-diffusion-webui\venv\lib\site-packages\h11\_state.py", line 238, in process_event
    self._fire_event_triggered_transitions(role, event_type)
  File "I:\stable-diffusion-webui\venv\lib\site-packages\h11\_state.py", line 251, in _fire_event_triggered_transitions
    raise LocalProtocolError(
h11._util.LocalProtocolError: can't handle event type ConnectionClosed when role=SERVER and state=SEND_RESPONSE
*** API error: POST: http://127.0.0.1:7860/run/predict {'error': 'LocalProtocolError', 'detail': '', 'body': '', 'errors': "Can't send data when our state is ERROR"}
    Traceback (most recent call last):
      File "I:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
        await self.app(scope, receive, _send)
      File "I:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 109, in __call__
        await response(scope, receive, send)
      File "I:\stable-diffusion-webui\venv\lib\site-packages\starlette\responses.py", line 270, in __call__
        async with anyio.create_task_group() as task_group:
      File "I:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 597, in __aexit__
        raise exceptions[0]
      File "I:\stable-diffusion-webui\venv\lib\site-packages\starlette\responses.py", line 273, in wrap
        await func()
      File "I:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 134, in stream_response
        return await super().stream_response(send)
      File "I:\stable-diffusion-webui\venv\lib\site-packages\starlette\responses.py", line 255, in stream_response
        await send(
      File "I:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\errors.py", line 159, in _send
        await send(message)
      File "I:\stable-diffusion-webui\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 490, in send
        output = self.conn.send(event=response)
      File "I:\stable-diffusion-webui\venv\lib\site-packages\h11\_connection.py", line 468, in send
        data_list = self.send_with_data_passthrough(event)
      File "I:\stable-diffusion-webui\venv\lib\site-packages\h11\_connection.py", line 483, in send_with_data_passthrough
        raise LocalProtocolError("Can't send data when our state is ERROR")
    h11._util.LocalProtocolError: Can't send data when our state is ERROR

---
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "I:\stable-diffusion-webui\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "I:\stable-diffusion-webui\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "I:\stable-diffusion-webui\venv\lib\site-packages\fastapi\applications.py", line 273, in __call__
    await super().__call__(scope, receive, send)
  File "I:\stable-diffusion-webui\venv\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "I:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "I:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "I:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 109, in __call__
    await response(scope, receive, send)
  File "I:\stable-diffusion-webui\venv\lib\site-packages\starlette\responses.py", line 270, in __call__
    async with anyio.create_task_group() as task_group:
  File "I:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "I:\stable-diffusion-webui\venv\lib\site-packages\starlette\responses.py", line 273, in wrap
    await func()
  File "I:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 134, in stream_response
    return await super().stream_response(send)
  File "I:\stable-diffusion-webui\venv\lib\site-packages\starlette\responses.py", line 255, in stream_response
    await send(
  File "I:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\errors.py", line 159, in _send
    await send(message)
  File "I:\stable-diffusion-webui\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 490, in send
    output = self.conn.send(event=response)
  File "I:\stable-diffusion-webui\venv\lib\site-packages\h11\_connection.py", line 468, in send
    data_list = self.send_with_data_passthrough(event)
  File "I:\stable-diffusion-webui\venv\lib\site-packages\h11\_connection.py", line 483, in send_with_data_passthrough
    raise LocalProtocolError("Can't send data when our state is ERROR")
h11._util.LocalProtocolError: Can't send data when our state is ERROR
