### ISSUE TITLE
[Bug] 右边的额外网络和已安装插件无限加载

### ISSUE THREAD

**Issue by NaughtDZ** [lobehub/sd-webui-lobe-theme#513]
### 👀 检查清单 | Initial checklist

- [X] 已经阅读了 [常见问题](https://github.com/lobehub/sd-webui-lobe-theme/issues/467) | I have read the [FAQ](https://github.com/lobehub/sd-webui-lobe-theme/issues/468)
- [X] 插件和 SD WebUI 均为为最新版本 | Plugin and SD WebUI both are the latest version
- [X] 插件的分支为 main | The branch of the plugin is main
- [X] 在单独开启插件的情况下，问题仍然存在 | The problem still exists when the plugin is turned on separately

### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Edge

### 🐛 问题描述 | Bug Description

以下是我用的插件，额外网络无限加载，已安装的扩展插件也是无限加载
2024/01/09 21:58

a1111-sd-webui-tagcomplete
2024/01/10 23:42 adetailer
2023/11/24 10:28 multidiffusion-upscaler-for-automatic1111
2024/01/06 23:52 OneButtonPrompt
2023/11/24 10:28 prompt_translator
2024/01/12 13:00 sd-civitai-browser-plus
2023/11/24 10:28 sd-webui-3d-open-pose-editor
2023/12/20 23:54 sd-webui-animatediff
2023/11/24 10:28 sd-webui-aspect-ratio-helper
2024/01/12 13:00 sd-webui-controlnet
2024/01/07 11:35 sd-webui-deepdanbooru-object-recognition
2023/11/24 10:30 sd-webui-depth-lib
2024/01/08 17:58 sd-webui-e621-prompt
2023/11/24 17:45 sd-webui-freeu
2024/01/12 18:41 sd-webui-infinite-image-browsing
2024/01/12 17:48 sd-webui-lobe-theme
2023/11/24 10:30 sd-webui-oldsix-prompt
2023/12/26 22:37 sd-webui-openpose-editor
2024/01/06 23:52 sd-webui-reactor
2023/11/24 10:28 sd_delete_button
2023/11/27 21:34 stable-diffusion-webui-localization-zh_CN
2023/11/24 10:30 stable-diffusion-webui-localization-zh_Hans
2023/11/24 10:30 stable-diffusion-webui-promptgen
2023/11/24 10:30 stable-diffusion-webui-state
2023/11/24 10:30 stable-diffusion-webui-wildcards
2024/01/07 11:39 ultimate-upscale-for-automatic1111
2023/11/24 10:30 webui-qrcode-generator

*******************************************************
亲测用--no-gradio-queue 可以解决但是会导致一堆报错：
To create a public link, set share=True in launch().
Loading VAE weights specified in settings: I:\stable-diffusion-webui\models\VAE\kl-f8-anime2.vae.pt
Applying attention optimization: xformers... done.
🤯 LobeTheme: Initializing...
Startup time: 38.0s (prepare environment: 14.1s, import torch: 4.8s, import gradio: 1.8s, setup paths: 1.2s, initialize shared: 0.3s, other imports: 1.0s, setup codeformer: 0.3s, list SD models: 0.2s, load scripts: 11.0s, create ui: 1.9s, gradio launch: 1.3s).
Model loaded in 7.6s (load weights from disk: 0.2s, create model: 1.0s, apply weights to model: 1.4s, load VAE: 0.3s, load textual inversion embeddings: 4.5s, calculate empty prompt: 0.1s).
ERROR:asyncio:Exception in callback H11Protocol.timeout_keep_alive_handler()
handle: <TimerHandle when=26031.187 H11Protocol.timeout_keep_alive_handler()>
Traceback (most recent call last):
File "I:\stable-diffusion-webui\venv\lib\site-packages\h11_state.py", line 249, in _fire_event_triggered_transitions
new_state = EVENT_TRIGGERED_TRANSITIONS[role][state][event_type]
KeyError: <class 'h11._events.ConnectionClosed'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Program Files\Python310\lib\asyncio\events.py", line 80, in _run
self._context.run(self._callback, *self._args)
File "I:\stable-diffusion-webui\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 363, in timeout_keep_alive_handler
self.conn.send(event)
File "I:\stable-diffusion-webui\venv\lib\site-packages\h11_connection.py", line 468, in send
data_list = self.send_with_data_passthrough(event)
File "I:\stable-diffusion-webui\venv\lib\site-packages\h11_connection.py", line 493, in send_with_data_passthrough
self._process_event(self.our_role, event)
File "I:\stable-diffusion-webui\venv\lib\site-packages\h11_connection.py", line 242, in _process_event
self._cstate.process_event(role, type(event), server_switch_event)
File "I:\stable-diffusion-webui\venv\lib\site-packages\h11_state.py", line 238, in process_event
self._fire_event_triggered_transitions(role, event_type)
File "I:\stable-diffusion-webui\venv\lib\site-packages\h11_state.py", line 251, in _fire_event_triggered_transitions
raise LocalProtocolError(
h11._util.LocalProtocolError: can't handle event type ConnectionClosed when role=SERVER and state=SEND_RESPONSE
*** API error: POST: http://127.0.0.1:7860/run/predict {'error': 'LocalProtocolError', 'detail': '', 'body': '', 'errors': "Can't send data when our state is ERROR"}
Traceback (most recent call last):
File "I:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\errors.py", line 162, in call
await self.app(scope, receive, _send)
File "I:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 109, in call
await response(scope, receive, send)
File "I:\stable-diffusion-webui\venv\lib\site-packages\starlette\responses.py", line 270, in call
async with anyio.create_task_group() as task_group:
File "I:\stable-diffusion-webui\venv\lib\site-packages\anyio_backends_asyncio.py", line 597, in aexit
raise exceptions[0]
File "I:\stable-diffusion-webui\venv\lib\site-packages\starlette\responses.py", line 273, in wrap
await func()
File "I:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 134, in stream_response
return await super().stream_response(send)
File "I:\stable-diffusion-webui\venv\lib\site-packages\starlette\responses.py", line 255, in stream_response
await send(
File "I:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\errors.py", line 159, in _send
await send(message)
File "I:\stable-diffusion-webui\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 490, in send
output = self.conn.send(event=response)
File "I:\stable-diffusion-webui\venv\lib\site-packages\h11_connection.py", line 468, in send
data_list = self.send_with_data_passthrough(event)
File "I:\stable-diffusion-webui\venv\lib\site-packages\h11_connection.py", line 483, in send_with_data_passthrough
raise LocalProtocolError("Can't send data when our state is ERROR")
h11._util.LocalProtocolError: Can't send data when our state is ERROR

ERROR: Exception in ASGI application
Traceback (most recent call last):
File "I:\stable-diffusion-webui\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 408, in run_asgi
result = await app( # type: ignore[func-returns-value]
File "I:\stable-diffusion-webui\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in call
return await self.app(scope, receive, send)
File "I:\stable-diffusion-webui\venv\lib\site-packages\fastapi\applications.py", line 273, in call
await super().call(scope, receive, send)
File "I:\stable-diffusion-webui\venv\lib\site-packages\starlette\applications.py", line 122, in call
await self.middleware_stack(scope, receive, send)
File "I:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\errors.py", line 184, in call
raise exc
File "I:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\errors.py", line 162, in call
await self.app(scope, receive, _send)
File "I:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 109, in call
await response(scope, receive, send)
File "I:\stable-diffusion-webui\venv\lib\site-packages\starlette\responses.py", line 270, in call
async with anyio.create_task_group() as task_group:
File "I:\stable-diffusion-webui\venv\lib\site-packages\anyio_backends_asyncio.py", line 597, in aexit
raise exceptions[0]
File "I:\stable-diffusion-webui\venv\lib\site-packages\starlette\responses.py", line 273, in wrap
await func()
File "I:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 134, in stream_response
return await super().stream_response(send)
File "I:\stable-diffusion-webui\venv\lib\site-packages\starlette\responses.py", line 255, in stream_response
await send(
File "I:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\errors.py", line 159, in _send
await send(message)
File "I:\stable-diffusion-webui\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 490, in send
output = self.conn.send(event=response)
File "I:\stable-diffusion-webui\venv\lib\site-packages\h11_connection.py", line 468, in send
data_list = self.send_with_data_passthrough(event)
File "I:\stable-diffusion-webui\venv\lib\site-packages\h11_connection.py", line 483, in send_with_data_passthrough
raise LocalProtocolError("Can't send data when our state is ERROR")
h11._util.LocalProtocolError: Can't send data when our state is ERROR

### 🚦 期望结果 | Expected Behavior

--no-gradio-queue虽然能让ui正常工作，但是带来的一堆报错可能会引发其他bug。希望本ui插件作者能研究出来为什么加了--no-gradio-queue就能解决这个问题，继而反向修复这个bug。

**Comment by kaalibro** [comment]
Try to uninstall the "sd-webui-depth-lib" and install it from this fork:
https://github.com/wywywywy/sd-webui-depth-lib

Please inform if the issue with `--no-gradio-queue` persists after reinstalling this extension.

**Comment by NaughtDZ** [comment]
> Try to uninstall the "sd-webui-depth-lib" and install it from this fork: https://github.com/wywywywy/sd-webui-depth-lib
> 
> Please inform if the issue with `--no-gradio-queue` persists after reinstalling this extension.
*********
Still error:
*************
To create a public link, set `share=True` in `launch()`.
🤯 LobeTheme: Initializing...
Startup time: 44.2s (prepare environment: 15.1s, import torch: 6.5s, import gradio: 2.5s, setup paths: 2.0s, initialize shared: 0.3s, other imports: 1.7s, setup codeformer: 0.4s, list SD models: 0.4s, load scripts: 9.9s, create ui: 4.0s, gradio launch: 1.0s, add APIs: 0.1s, app_started_callback: 0.1s).
Loading VAE weights specified in settings: I:\stable-diffusion-webui\models\VAE\kl-f8-anime2.vae.pt
Applying attention optimization: xformers... done.
ERROR:asyncio:Exception in callback H11Protocol.timeout_keep_alive_handler()
handle: <TimerHandle when=52773.156 H11Protocol.timeout_keep_alive_handler()>
Traceback (most recent call last):
  File "I:\stable-diffusion-webui\venv\lib\site-packages\h11\_state.py", line 249, in _fire_event_triggered_transitions
    new_state = EVENT_TRIGGERED_TRANSITIONS[role][state][event_type]
KeyError: <class 'h11._events.ConnectionClosed'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "I:\stable-diffusion-webui\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 363, in timeout_keep_alive_handler
    self.conn.send(event)
  File "I:\stable-diffusion-webui\venv\lib\site-packages\h11\_connection.py", line 468, in send
    data_list = self.send_with_data_passthrough(event)
  File "I:\stable-diffusion-webui\venv\lib\site-packages\h11\_connection.py", line 493, in send_with_data_passthrough
    self._process_event(self.our_role, event)
  File "I:\stable-diffusion-webui\venv\lib\site-packages\h11\_connection.py", line 242, in _process_event
    self._cstate.process_event(role, type(event), server_switch_event)
  File "I:\stable-diffusion-webui\venv\lib\site-packages\h11\_state.py", line 238, in process_event
    self._fire_event_triggered_transitions(role, event_type)
  File "I:\stable-diffusion-webui\venv\lib\site-packages\h11\_state.py", line 251, in _fire_event_triggered_transitions
    raise LocalProtocolError(
h11._util.LocalProtocolError: can't handle event type ConnectionClosed when role=SERVER and state=SEND_RESPONSE
Model loaded in 20.1s (load weights from disk: 1.0s, create model: 0.6s, apply weights to model: 13.6s, load VAE: 1.4s, load textual inversion embeddings: 3.0s, calculate empty prompt: 0.4s).
*** API error: POST: http://127.0.0.1:7860/run/predict {'error': 'LocalProtocolError', 'detail': '', 'body': '', 'errors': "Can't send data when our state is ERROR"}
    Traceback (most recent call last):
      File "I:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
        await self.app(scope, receive, _send)
      File "I:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 109, in __call__
        await response(scope, receive, send)
      File "I:\stable-diffusion-webui\venv\lib\site-packages\starlette\responses.py", line 270, in __call__
        async with anyio.create_task_group() as task_group:
      File "I:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 597, in __aexit__
        raise exceptions[0]
      File "I:\stable-diffusion-webui\venv\lib\site-packages\starlette\responses.py", line 273, in wrap
        await func()
      File "I:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 134, in stream_response
        return await super().stream_response(send)
      File "I:\stable-diffusion-webui\venv\lib\site-packages\starlette\responses.py", line 255, in stream_response
        await send(
      File "I:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\errors.py", line 159, in _send
        await send(message)
      File "I:\stable-diffusion-webui\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 490, in send
        output = self.conn.send(event=response)
      File "I:\stable-diffusion-webui\venv\lib\site-packages\h11\_connection.py", line 468, in send
        data_list = self.send_with_data_passthrough(event)
      File "I:\stable-diffusion-webui\venv\lib\site-packages\h11\_connection.py", line 483, in send_with_data_passthrough
        raise LocalProtocolError("Can't send data when our state is ERROR")
    h11._util.LocalProtocolError: Can't send data when our state is ERROR

---
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "I:\stable-diffusion-webui\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "I:\stable-diffusion-webui\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "I:\stable-diffusion-webui\venv\lib\site-packages\fastapi\applications.py", line 273, in __call__
    await super().__call__(scope, receive, send)
  File "I:\stable-diffusion-webui\venv\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "I:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "I:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "I:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 109, in __call__
    await response(scope, receive, send)
  File "I:\stable-diffusion-webui\venv\lib\site-packages\starlette\responses.py", line 270, in __call__
    async with anyio.create_task_group() as task_group:
  File "I:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "I:\stable-diffusion-webui\venv\lib\site-packages\starlette\responses.py", line 273, in wrap
    await func()
  File "I:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 134, in stream_response
    return await super().stream_response(send)
  File "I:\stable-diffusion-webui\venv\lib\site-packages\starlette\responses.py", line 255, in stream_response
    await send(
  File "I:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\errors.py", line 159, in _send
    await send(message)
  File "I:\stable-diffusion-webui\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 490, in send
    output = self.conn.send(event=response)
  File "I:\stable-diffusion-webui\venv\lib\site-packages\h11\_connection.py", line 468, in send
    data_list = self.send_with_data_passthrough(event)
  File "I:\stable-diffusion-webui\venv\lib\site-packages\h11\_connection.py", line 483, in send_with_data_passthrough
    raise LocalProtocolError("Can't send data when our state is ERROR")
h11._util.LocalProtocolError: Can't send data when our state is ERROR

**Comment by NaughtDZ** [comment]
额外说一下，加--no-gradio-queue会导致Civit AI Browser插件下载出问题，这可没法取舍了。只能要下载或者更新模型时候去掉启动项，然后再加回来，非常麻烦

**Comment by herbieliang** [comment]
请问这个问题有解决方案了吗？
